[tools]
java = "corretto-21"
jj = "latest"
rust = "latest"
kotlin = "2"
"npm:cdktf" = "latest"
"npm:cdktf-cli" = { version = "latest", node = "22" }

[settings]
# Enable automatic .tool-versions creation for tools     
# empty = let mise manage versions automatically         
#idiomatic_version_file_enable_tools = ["python", "java"]
idiomatic_version_file_enable_tools = [] 

[settings.ruby]
compile = false

[env]
# Environment variables to set when using tools managed by mise
#.MISE_DIFF = "true" 
#.MISE_TRUSTED_CONFIG = "true"
