# /etc/tlp.conf
# Optimize for battery life when unplugged

# CPU frequency scaling governor
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave

# Restrict turbo boost on battery to save power and reduce heat
CPU_BOOST_ON_BAT=0

# Limit maximum CPU performance state on battery (percentage)
CPU_MAX_PERF_ON_BAT=75

# PCIe active state power management
PCIE_ASPM_ON_BAT=powersupersave

# --- ThinkPad Battery Care ---
# Target BAT0 (Internal) and BAT1 (Secondary/Ultrabay)
# Start charging when below 75%, stop charging at 80%
START_CHARGE_THRESH_BAT0=75
STOP_CHARGE_THRESH_BAT0=80
START_CHARGE_THRESH_BAT1=75
STOP_CHARGE_THRESH_BAT1=80

# --- Audio Power Saving ---
# Timeout in seconds before the audio chip goes to sleep
SOUND_POWER_SAVE_ON_AC=10
SOUND_POWER_SAVE_ON_BAT=5

# Disable controller too (HDA specific)
SOUND_POWER_SAVE_CONTROLLER=Y

# Increase the time before writing to disk to save power on battery
MAX_LOST_WORK_SECS_ON_BAT=60

# Aggressive link power management (ALPM) für SATA.
# min_power ist für den Akkubetrieb auf Skylake optimal.
SATA_LINKPWR_ON_BAT="min_power"

# --- Keep a bit of performance on battery ---
# Don't save on Wifi power.
WIFI_PWR_ON_BAT=off
# A bit more CPU performance on battery, to keep the system responsive.
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_performance
