# See resolved.conf(5) for details.

[Resolve]
# Primary IPv4 and IPv6 DNS servers (Quad9 with malware filtering)
# Appending #domain is required for certificate validation in DoT
DNS=9.9.9.9#dns.quad9.net 2620:fe::fe#dns.quad9.net

# Fallback DNS servers (Mulvad-DNS with malware filtering)
FallbackDNS=194.242.2.2#dns.mullvad.net 2a07:e340::2#dns.mullvad.net

# Enable DNS-over-TLS (opportunistic od strict mode)
# 'yes' enforces DoT and fails if the server doesn't support it, 'opportunistic' falls back to plaintext if DoT isn't available
DNSOverTLS=yes

# Enable local DNS caching to improve performance and reduce latency
Cache=yes

# DNSSEC validation (optional, but recommended for security)
# 'allow-downgrade' validates if supported, but allows unsigned responses
DNSSEC=allow-downgrade

# Set global domains to '~.' to ensure global DNS servers are preferred for all queries
#Domains=~.

# Disable reading DNS servers from network interfaces is done in systemd-networkd
# configuration via UseDNS=no in [DHCP], [DHCPv6] and [IPv6AcceptRA] sections.
# ReadEtcHosts determines if /etc/hosts is used.
ReadEtcHosts=yes
