# Main Alacritty configuration
# Import OS-specific overrides. Alacritty will silently ignore missing files.
[general]
import = [
    "~/.config/alacritty/alacritty_local.toml"
]
live_config_reload = true

[colors.bright]
black = "#353539"
blue = "#b9aeda"
cyan = "#f591b2"
green = "#9dc6ac"
magenta = "#ecaad6"
red = "#ffae9f"
white = "#cac9dd"
yellow = "#f0c5a9"

[colors.cursor]
cursor = "#757581"
text = "#c9c7cd"

[cursor]
style = { shape = "Block", blinking = "Never" }

[colors.normal]
black = "#27272a"
blue = "#aca1cf"
cyan = "#ea83a5"
green = "#90b99f"
magenta = "#e29eca"
red = "#f5a191"
white = "#c1c0d4"
yellow = "#e6b99d"

[colors.primary]
background = "#161617"
foreground = "#c9c7cd"

[env]
#TERM = "xterm-256color"
TERM = "alacritty"

[font]
normal      = { family = "BerkeleyMono Nerd Font Mono", style = "Regular" }
bold        = { family = "BerkeleyMono Nerd Font Mono", style = "Bold" }
italic      = { family = "BerkeleyMono Nerd Font Mono", style = "Oblique" }
bold_italic = { family = "BerkeleyMono Nerd Font Mono", style = "Bold Oblique" }

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 135
lines = 50

[window.padding]
x = 7
y = 5

[window.position]
x = 290
y = 800

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
